export let selectedItem = $state({
  item: 1,
});

export const medList = [
  {
    Item: 1,
    Name: "CoCal Lozenges",
    Composition: ["Calcium Carbonate 800 mg", "Equivalent to 320 mg Elemental Calcium"],
    KeyPoint: [
      "Calcium Deficiency",
      "Pregnancy & Lactation",
      "Suitable For All Age Groups",
      "High Dose Compliance",
      "Low Glycemic Load",
    ],
  },
  {
    Item: 2,
    Name: "Gabadron-NT Tab",
    Composition: ["Pregabaline 75 mg", "Nortriptyline Hydrochloride 10mg"],
    KeyPoint: [
      "Neuropathic Pain Associated with",
      "Spondylitis",
      "Arthritis",
      "Sciatica",
      "Diabetic Neuropathy",
      "Peripherial Neuropathy",
      "Drug-Induced Neuropathy",
    ],
  },
  {
    Item: 3,
    Name: "Gabadron-plus Tab",
    Composition: [
      "Vitamin D3 - 1000 IU",
      "Methylcobalamin - 1500mcg",
      "Vitamin B6 - 3mg",
      "Alpha Lipoic Acid - 100mg",
      "Folic Acid - 5mg",
    ],
    KeyPoint: [
      "Vitamin D3 and B12 deficiency",
      "Post Traumatic Neuropathy",
      "Alcoholic Neuropathy",
      "Post Herpatic Neuralgia",
      "Diabetic Neuropathy",
      "Drug-Induced Neuropathy",
    ],
  },
  {
    Item: 4,
    Name: "Gabadron-M Cap",
    Composition: [
      "Pregabalin - 75mg",
      "Methylcobalamin - 1500mcg",
      "Vitamin B6 - 3mg",
      "Alpha Lipoic Acid - 100mg",
      "Folic Acid - 5mg",
    ],
    KeyPoint: [
      "Post Traumatic Neuropathy",
      "Alcoholic Neuropathy",
      "Post Herpatic Neuralgia",
      "Diabetic Neuropathy",
      "Drug Induced Neuropathy",
    ],
  },
  {
    Item: 5,
    Name: "Gabadron - 12G Cap",
    Composition: [
      "Omega-3 Fatty Acid",
      "Green Tea Extract",
      "Ginkgo Biloba Extract",
      "Ginseng Extract",
      "Grape Seed Extract",
      "Multimineral",
      "Multivitamin With Antioxidant & Trace Elements Softgel Capsules",
    ],
    KeyPoint: [
      "Fatigue and Tiredness",
      "Protect against oxidative Stress",
      "Strengthen Immune System",
      "Useful In Chronic Diseases",
    ],
  },
  {
    Item: 6,
    Name: "Hydflam Tab",
    Composition: [
      "50,000 Armour units of Enzymatic Activity (Trypsin and Chymotrypsin ratio 6:1)",
      "Diclofenac Potassium B.P. 50mg",
      "Paracetamol 325mg",
    ],
    KeyPoint: [
      "Soft tissue injury",
      "Post-traumatic oedema",
      "Viral Arthritis",
      "Tooth extraction",
      "Burn",
      "Cuts",
      "Wounds",
    ],
  },
  {
    Item: 7,
    Name: "Hydflam MR Tab",
    Composition: ["Thiocolchicoside 4mg", "Aceclofenac 100mg"],
    KeyPoint: [
      "Low back pain",
      "Neck pain",
      "Muscle Spasm associated with Trauma",
      "Dorsal pain",
      "Vertebral static problem",
      "Skeletal Muscle Spasm",
    ],
  },
  {
    Item: 8,
    Name: "Hydflam SP Tab",
    Composition: ["Aceclofenac 100mg", "Paracetamol 325mg", "Serratiopeptidase 15mg"],
    KeyPoint: [
      "Easy relief in Fractures",
      "Dislocations",
      "Trauma",
      "Tooth Extraction",
      "Tendinitis",
      "Soft tissue injuries",
    ],
  },
  {
    Item: 9,
    Name: "MLuk Tab",
    Composition: ["Montelukast sodium 10mg", "levocetirizine dihydrochloride 5mg"],
    KeyPoint: [
      "Allergic rhinitis",
      "Asthma & Bronchitis",
      "Cough and cold",
      "Sneezing",
      "Running nose",
      "Itchy throat and nose",
      "Fever and body pain",
    ],
  },
  {
    Item: 10,
    Name: "MLuk-AF Tab",
    Composition: ["Montelukast 10mg", "Fexofenadine 120mg", "Acebrophyline 200mg (S.R)"],
    KeyPoint: [
      "Allergic rhinitis",
      "Asthma & Bronchitis",
      "Cough and cold",
      "Sneezing",
      "Running nose",
      "Itchy throat and nose",
    ],
  },
  {
    Item: 11,
    Name: "Mluk COLD Tab",
    Composition: ["Phenylephrine Hcl 10mg", "Chlorpheniramine Maleate 2 mg", "Paracelamol 500 mg"],
    KeyPoint: [
      "Allergic rhinitis",
      "Bronchitis",
      "Cough and cold",
      "Sneezing",
      "Running nose",
      "Itchy throat and nose",
      "Fever and body pain",
    ],
  },
  {
    Item: 12,
    Name: "GI-OK Sachet",
    Composition: [
      "(Saccharomyces Boulardi Lactobacillus Rhamnosus, Lactobacillus Acidophilus, Bifidobacterium Longum, Bifidobacterium Infantis ) 1.3 bilion CFU",
      "Elemental zinc 10 mg",
      "Fructo Oligo Saccharides (fos)100 mg",
    ],
    KeyPoint: ["Pediatric Diarrhoea", "Lactose Intolerance", "Gastroenteritis"],
  },
  {
    Item: 13,
    Name: "GI-OK Capsule",
    Composition: [
      "Streptococcus faecalis T110-30 million",
      "Clostridium butyricum T0A-2 million",
      "Bacillus mesentericus TOA-1 Million",
      "Lactic Acid Bacillus - 50 Million (Lactobacillus sporogenes)",
    ],
    KeyPoint: [
      "Diarrhea",
      "Along with Antibiotic treatments",
      "Irritable bowel syndrome",
      "Boosts the immune system",
      "Drug-induced Diarrhea",
      "Ulcers in the digestive tract",
    ],
  },
  {
    Item: 14,
    Name: "Defth 6",
    Composition: ["Deflazacort 6 mg "],
    KeyPoint: ["Asthma and Bronchitis", "Chronic Arthritis", "Hypersensitivity Reaction"],
  },
  {
    Item: 15,
    Name: "Aimena Tab",
    Composition: ["Ferrous ascorbate 100mg", "Folic acid 5mg", "Methylcobalamin 750mcg", "Zinc Sulphate 22.5mg"],
    KeyPoint: [
      "Pregnancy & Lactation",
      "Iron deficiency anemia",
      "Worm infection",
      "Postoperative convalescence",
      "To boost immunity",
    ],
  },
  {
    Item: 16,
    Name: "KARBOCAL Tab",
    Composition: ["Calcium Citrate 1000mg", "Vitamin D3 2000 I.U.", "Magnesium 100mg", "Zinc 7.5mg"],
    KeyPoint: [
      "Calcium and Vitamin D3 Deficiency",
      "Prevention & Treatment of Osteoporosis",
      "Pregnancy & Lactation",
      "Post Menopausal Osteoporosis",
    ],
  },
  {
    Item: 17,
    Name: "AiKON CV Dry Syrup",
    Composition: ["Amoxycillin 200 mg", "Clavulanic Acid 28.5 mg"],
    KeyPoint: [
      "Upper respiratory tract infection",
      "Lower respiratory tract infection",
      "Acute Bacterial Sinusitis",
      "Otitis Media",
      "AECB",
      "CAP",
      "UTI",
      "LRTI",
    ],
  },
  {
    Item: 18,
    Name: "AiKON CV - 625 Tab",
    Composition: ["Amoxycillin 500 mg", "Potassium Clavulanic Acid 125 mg"],
    KeyPoint: [
      "Upper respiratory tract infection",
      "Lower respiratory tract infection",
      "Acute Bacterial Sinusitis",
      "Otitis Media",
      "AECB",
      "CAP",
      "UTI",
      "LRTI",
    ],
  },
  {
    Item: 19,
    Name: "AiKON CV Forte Syrup",
    Composition: ["Amoxycillin 400 mg", "Clavulanic Acid 57 mg"],
    KeyPoint: [
      "Upper respiratory tract infection",
      "Lower respiratory tract infection",
      "Acute Bacterial Sinusitis",
      "Otitis Media",
      "AECB",
      "CAP",
      "UTI",
      "LRTI",
    ],
  },

  {
    Item: 20,
    Name: "Azyron - 250 Tab",
    Composition: ["Azithromycin 250 "],
    KeyPoint: [
      "Pneumonia",
      "Pharyngitis & Laryngitis",
      "Tonsillitis",
      "Acute Bacterial Sinusitis",
      "Acute Otitis Media",
      "SSTI",
      "AECB",
    ],
  },
  {
    Item: 21,
    Name: "Azyron - 500 Tab",
    Composition: ["Azithromycin 500 "],
    KeyPoint: [
      "Pneumonia",
      "Pharyngitis & Laryngitis",
      "Tonsillitis",
      "Acute Bacterial Sinusitis",
      "Acute Otitis Media",
      "SSTI",
      "AECB",
    ],
  },
  {
    Item: 22,
    Name: "HYDKOF DX Syrup",
    Composition: ["Dextromethorphan 10mg", "Phenylephrine 5 mg", "Chlorpheniramine Maleate 2 mg"],
    KeyPoint: ["Dry Cough", "Sore Throat", "Allergic Cough"],
  },
  {
    Item: 23,
    Name: "HYDKOF Syrup",
    Composition: ["Ambroxol 15mg", "Terbutaline HCL 1.25mg", "Guaiphenesin 50mg", "Menthol Flavored Syrup base"],
    KeyPoint: [
      "Clear Mucous effectively",
      "Selectively Dilates the Bronchi & improves breathing",
      "Provides quick relief in Productive cough",
      "Acute & Chronic Bronchitis",
      "Smokers Cough",
      "Asthmatic Bronchitis",
    ],
  },
  {
    Item: 24,
    Name: "Hydpan 40 Tab",
    Composition: ["Pantoprazole 40mg "],
    KeyPoint: [
      "Drug-Induced Gastritis",
      "Reflux Oesophagitis",
      "Peptic Ulcers",
      "Chronic Gastritis",
      "H. pylori infection",
    ],
  },
  {
    Item: 25,
    Name: "Hydpan DSR Cap",
    Composition: ["Pantoprazole 40mg", "Domperidone 30mg"],
    KeyPoint: ["Domperidone 30mg relieves dysmotility of the gut", "Pantoprazole 40mg controls hyperacidity"],
  },
  {
    Item: 26,
    Name: "Hydrab-DSR Capsule",
    Composition: ["Rabeprazole Sodium 20mg", "Domperidone 30 mg sustained release"],
    KeyPoint: [
      "Drug-Induced Gastritis",
      "Reflux Oesophagitis",
      "Peptic Ulcers",
      "Chronic Gastritis",
      "H. pylori Infection",
    ],
  },
  {
    Item: 27,
    Name: "Hydrab-20",
    Composition: ["Rabeprazole Sodium 20mg "],
    KeyPoint: [
      "Drug-Induced Gastritis",
      "Reflux Oesophagitis",
      "Peptic Ulcers",
      "Chronic Gastritis",
      "H. pylori Infection",
    ],
  },
  {
    Item: 28,
    Name: "Hydrab-D Tab",
    Composition: ["Rabeprazole Sodium 20mg", "Domperidone 10mg"],
    KeyPoint: [
      "Drug-Induced Gastritis",
      "Reflux Oesophagitis",
      "Peptic Ulcers",
      "Chronic Gastritis",
      "H. pylori Infection",
    ],
  },
  {
    Item: 29,
    Name: "DOLOAID-P Tab",
    Composition: ["Aceclofenac 100mg", "Paracetamol 325mg "],
    KeyPoint: ["Lower back pain", "Fever and body pain", "Sport injury", "Acure Dental pain"],
  },
  {
    Item: 30,
    Name: "Karboz Tab",
    Composition: ["Ofloxacin 200 mg", "Ornidazole 500 mg"],
    KeyPoint: [
      "Diarrhoea and Dysentery",
      "Post MTP",
      "Leucorrhoea",
      "Urinary tract infection",
      "PID",
      "Infection of lower reproductive tract",
    ],
  },
];
